// Generated by BiocJobs 0.99.0 from the 'plot-coldata' job declared in
// Bioconductor package scater (inst/biocjobs/). Do not edit;
// regenerate with: Rscript -e 'BiocJobs::biocjobsCLI()' nextflow <pkg> plot-coldata

process PLOT_COLDATA {
    tag "${meta.id}"
    container 'bioconductor/bioconductor_docker:RELEASE_3_23'
    cpus 1
    memory '4 GB'
    disk '10 GB'

    input:
    // meta: map identifying the unit of work; meta.id names the tag
    // infile: Short UI label (h5ad)
    tuple val(meta), path(infile, name: 'infile.h5ad')
    // Name of metadata to plot on the Y-axis (string; required)
    val y
    // Plot width (inches) (float; default in spec: 3)
    val width
    // Plot height (inches) (float; default in spec: 5)
    val height

    output:
    tuple val(meta), path('outfile.pdf'), emit: outfile

    script:
    """
    Rscript -e 'BiocJobs::execJob("scater", "plot-coldata")' \\
        --infile '${(infile as String).replace("'", "'\\''")}' \\
        --y '${(y as String).replace("'", "'\\''")}' \\
        --width '${(width as String).replace("'", "'\\''")}' \\
        --height '${(height as String).replace("'", "'\\''")}' \\
        --outfile 'outfile.pdf'
    """

    stub:
    """
    touch 'outfile.pdf'
    """
}
