// Generated by BiocJobs 0.99.0 from the 'read-10x-counts' job declared in
// Bioconductor package DropletUtils (inst/biocjobs/). Do not edit;
// regenerate with: Rscript -e 'BiocJobs::biocjobsCLI()' nextflow <pkg> read-10x-counts

process READ_10X_COUNTS {
    tag "${meta.id}"
    container 'ghcr.io/kevinrue/dropletutils:devel'
    cpus 1
    memory '4 GB'
    disk '10 GB'

    input:
    // meta: map identifying the unit of work; meta.id names the tag
    // mtx_file: Raw count matrix (txt)
    // barcodes_file: Cell barcodes (tsv)
    // features_file: Feature annotations (tsv)
    // hdf5_file: HDF5 file (h5)
    tuple val(meta), path(mtx_file), path(barcodes_file), path(features_file), path(hdf5_file)
    // Input type (string; default in spec: mtx; required)
    val type
    // Sample name (string; required)
    val sample_name

    output:
    tuple val(meta), path('outfile.h5'), emit: outfile

    script:
    """
    Rscript -e 'BiocJobs::execJob("DropletUtils", "read-10x-counts")' \\
        --mtx_file '${(mtx_file as String).replace("'", "'\\''")}' \\
        --barcodes_file '${(barcodes_file as String).replace("'", "'\\''")}' \\
        --features_file '${(features_file as String).replace("'", "'\\''")}' \\
        --hdf5_file '${(hdf5_file as String).replace("'", "'\\''")}' \\
        --type '${(type as String).replace("'", "'\\''")}' \\
        --sample_name '${(sample_name as String).replace("'", "'\\''")}' \\
        --outfile 'outfile.h5'
    """

    stub:
    """
    touch 'outfile.h5'
    """
}
