// Generated by BiocJobs 0.99.0 from the 'read-10x-counts-h5' job declared in
// Bioconductor package DropletUtils (inst/biocjobs/). Do not edit;
// regenerate with: Rscript -e 'BiocJobs::biocjobsCLI()' nextflow <pkg> read-10x-counts-h5

process READ_10X_COUNTS_H5 {
    tag "${meta.id}"
    container 'ghcr.io/kevinrue/dropletutils:devel'
    cpus 1
    memory '4 GB'
    disk '10 GB'

    input:
    // meta: map identifying the unit of work; meta.id names the tag
    // hdf5_file: HDF5 file (h5)
    tuple val(meta), path(hdf5_file)
    // Sample name (string; required)
    val sample_name

    output:
    tuple val(meta), path('outfile.h5ad'), emit: outfile

    script:
    """
    Rscript -e 'BiocJobs::execJob("DropletUtils", "read-10x-counts-h5")' \\
        --hdf5_file '${(hdf5_file as String).replace("'", "'\\''")}' \\
        --sample_name '${(sample_name as String).replace("'", "'\\''")}' \\
        --outfile 'outfile.h5ad'
    """

    stub:
    """
    touch 'outfile.h5ad'
    """
}
