// Generated by BiocJobs 0.99.0 from the 'rna-qc' job declared in
// Bioconductor package scrapper (inst/biocjobs/). Do not edit;
// regenerate with: Rscript -e 'BiocJobs::biocjobsCLI()' nextflow <pkg> rna-qc

process RNA_QC {
    tag "${meta.id}"
    container 'ghcr.io/kevinrue/scrapper:devel'
    cpus 1
    memory '4 GB'
    disk '10 GB'

    input:
    // meta: map identifying the unit of work; meta.id names the tag
    // infile: SingleCellExperiment (h5ad)
    tuple val(meta), path(infile, name: 'infile.h5ad')
    // Mitochondrial gene prefix (string; default in spec: MT-)
    val mitochondrial_prefix
    // Number of MADs (float; default in spec: 3)
    val num_mads

    output:
    tuple val(meta), path('outfile.h5ad'), emit: outfile
    tuple val(meta), path('qc_table.tsv'), emit: qc_table

    script:
    """
    Rscript -e 'BiocJobs::execJob("scrapper", "rna-qc")' \\
        --infile '${(infile as String).replace("'", "'\\''")}' \\
        --mitochondrial_prefix '${(mitochondrial_prefix as String).replace("'", "'\\''")}' \\
        --num_mads '${(num_mads as String).replace("'", "'\\''")}' \\
        --outfile 'outfile.h5ad' \\
        --qc_table 'qc_table.tsv'
    """

    stub:
    """
    touch 'outfile.h5ad'
    touch 'qc_table.tsv'
    """
}
